[package]
name = "zero"
version = "0.1.0"
edition = "2021"


[dependencies]
futures = "0.3"
docopt = "1"
actix-files = "0.6.1"
actix = "0.13.0"
actix-web = "4.1.0"
actix-web-actors = "4.1.0"
serde = { version = "1", features = ["derive"] }
