[package]
name = "zero"
version = "0.1.0"
edition = "2021"


[dependencies]
futures = "0.3"
docopt = "1"
actix = "0.10"
actix-files = "0.5.0"
actix-web = "3"
actix-web-actors = "3"
serde = { version = "1", features = ["derive"] }
