<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit15240181c935fc9ab6566311917eaf1d
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Workerman\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Workerman\\' => 
        array (
            0 => __DIR__ . '/..' . '/workerman/workerman',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit15240181c935fc9ab6566311917eaf1d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit15240181c935fc9ab6566311917eaf1d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
