name: publish-dockerhub
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      image_tag:
        description: "tag of docker image"
        required: false 
        default: "latest"

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push(git push)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cupen/zero:latest
        if: github.event_name == 'push'

      - name: Build and push(manual)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cupen/protoc:${{ github.event.inputs.image_tag }}
        if: github.event_name == 'workflow_dispatch'
